name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: docker

    container:
      image: data.forgejo.org/oci/node:20-bullseye

    env:
      FLUTTER_VERSION: "3.38.7"
      ANDROID_SDK_ROOT: /android-sdk
      ANDROID_HOME: /android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y curl unzip zip git openjdk-17-jdk libglu1-mesa

      - name: Install Flutter
        run: |
          curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz \
            -o flutter.tar.xz
          tar xf flutter.tar.xz
          mv flutter /flutter
          git config --global --add safe.directory /flutter
          export PATH="/flutter/bin:$PATH"
          echo "/flutter/bin" >> $GITHUB_PATH

          flutter --version

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT
          curl -L https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip \
            -o cmdline-tools.zip
          unzip cmdline-tools.zip -d /tmp
          mv /tmp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          sdkmanager --version

      - name: Install SDK packages & accept licenses
        run: |
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Flutter doctor
        run: |
          export PATH="/flutter/bin:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          flutter doctor -v

      - name: Build APK
        run: |
          export PATH="/flutter/bin:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          flutter pub get
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
